export const dynamic = "force-dynamic"

import { NextRequest, NextResponse } from 'next/server'
import { getFullCompliancePackage, US_STATES } from '@/lib/compliance-engine'

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const {
      employeeName, position, department, startDate, workState,
      salary, salaryType = 'annual', companyName = 'Acme Corp',
      supervisorName, officeLocation
    } = body

    const stateName = US_STATES.find(s => s.code === workState)?.name || workState
    const pkg = getFullCompliancePackage(workState)

    const stateClause = getStateSpecificClause(workState, stateName, salary, salaryType)
    const atWillClause = getAtWillClause(workState, stateName)
    const complianceNotices = getComplianceNotices(workState)

    const letterDate = new Date().toLocaleDateString('en-US', {
      year: 'numeric', month: 'long', day: 'numeric'
    })

    const offerLetter = `
OFFER LETTER

${letterDate}

${employeeName}
[Address on File]

Dear ${employeeName},

We are pleased to offer you the position of ${position}${department ? ` in the ${department} department` : ''} at ${companyName}. This letter outlines the terms and conditions of your employment.

POSITION & START DATE
Your employment will begin on ${startDate}. Your primary work location will be ${officeLocation || stateName}.
${supervisorName ? `You will report directly to ${supervisorName}.` : ''}

COMPENSATION
${salary ? `Your ${salaryType === 'annual' ? 'annual salary' : 'hourly rate'} will be ${salaryType === 'annual' ? `$${parseInt(salary).toLocaleString()} per year` : `$${salary} per hour`}, payable in accordance with our standard payroll schedule.` : 'Compensation details will be discussed and confirmed separately.'}

${stateClause}

EMPLOYMENT RELATIONSHIP
${atWillClause}

BENEFITS
You will be eligible for our company benefits package, details of which will be provided separately. Benefits eligibility may be subject to waiting periods as specified in our Employee Handbook.

COMPLIANCE NOTICES
${complianceNotices}

CONFIDENTIAL INFORMATION
As a condition of your employment, you agree to maintain the confidentiality of ${companyName}'s proprietary information, trade secrets, and confidential business information both during and after your employment.

BACKGROUND CHECK
This offer is contingent upon successful completion of a background check as permitted by applicable law in ${stateName}.

ONBOARDING
Before your first day, you will receive a link to complete your new hire compliance documentation. ALL required federal and state documents must be completed before you are cleared to begin work.

CONDITIONS OF OFFER
This offer is contingent upon:
1. Completion of all required I-9 employment eligibility verification documents
2. Completion of all required ${stateName} state compliance documentation
3. Successful background check
4. Signing of required company agreements

Please confirm your acceptance of this offer by signing below and returning a copy to HR within 5 business days.

We look forward to welcoming you to the ${companyName} team.

Sincerely,

_______________________________
HR Department
${companyName}


ACCEPTANCE

I, ${employeeName}, accept the terms and conditions of this offer of employment.

Signature: _______________________________    Date: _______________

Printed Name: _______________________________

---
IMPORTANT LEGAL NOTICES FOR ${stateName.toUpperCase()} EMPLOYEES:
${pkg.state?.notes.join('\n') || 'Please review all applicable federal and state employment laws.'}

This offer letter was generated by HireProof Compliance System. It does not constitute legal advice. Please consult with an employment attorney for guidance specific to your situation.
`

    return NextResponse.json({
      offerLetter,
      state: workState,
      stateName,
      complianceRequirements: pkg.allRequirements.length,
      generatedAt: new Date().toISOString()
    })
  } catch {
    return NextResponse.json({ error: 'Failed to generate offer letter' }, { status: 500 })
  }
}

function getStateSpecificClause(state: string, stateName: string, salary: string, salaryType: string): string {
  const clauses: Record<string, string> = {
    CA: `CALIFORNIA-SPECIFIC DISCLOSURES (Required under SB 1162 & Labor Code §432.3)
Pay Scale: The pay scale for this position is ${salary ? `$${parseInt(salary).toLocaleString()} ${salaryType === 'annual' ? 'per year' : 'per hour'}` : '[to be disclosed per California law]'}. You have the right to request pay scale information for any position you hold or apply for at any time.
Non-Compete: Any non-compete agreements are void and unenforceable under California Business & Professions Code §16600.
Pay Transparency: Per California Labor Code §432.3, salary history has not been considered in this offer.`,
    NY: `NEW YORK-SPECIFIC DISCLOSURES (Required under NY Labor Law §194-b)
Compensation Range: The compensation range for this position is disclosed in compliance with NY Pay Transparency Law (S9427A, 2023).
At-Will Notice: This employment is at-will as permitted under New York law.`,
    CO: `COLORADO-SPECIFIC DISCLOSURES (Required under C.R.S. §8-5-101)
Pay Range Disclosure: Pursuant to the Colorado Equal Pay for Equal Work Act (SB 19-085), the compensation for this position is ${salary ? `$${parseInt(salary).toLocaleString()} ${salaryType === 'annual' ? 'annually' : 'per hour'}` : '[as disclosed in the job posting]'}.
Benefits Summary: A complete benefits description is available upon request.`,
    WA: `WASHINGTON STATE DISCLOSURES (Required under RCW §49.58.010)
Compensation: Per the Washington Equal Pay and Opportunities Act, the wage/salary range for this position is ${salary ? `$${parseInt(salary).toLocaleString()} ${salaryType === 'annual' ? 'per year' : 'per hour'}` : '[as disclosed]'}.
Pay Equity: The Company complies with Washington's Equal Pay and Opportunities Act.`,
    IL: `ILLINOIS DISCLOSURES (Workplace Transparency Act, SB 75)
Pay Information: Compensation details are provided in compliance with Illinois pay transparency requirements.
Non-Disclosure Limitations: Per the Illinois Workplace Transparency Act, certain non-disclosure provisions are limited.`
  }

  return clauses[state] || ''
}

function getAtWillClause(state: string, stateName: string): string {
  if (state === 'MT') {
    return `MONTANA EMPLOYMENT NOTICE — IMPORTANT: Montana is the only state that prohibits at-will termination after completion of the probationary period. Your probationary period is 6 months from your start date. During the probationary period, employment may be terminated at will. After successful completion of the probationary period, you may only be terminated for "good cause" as defined under the Montana Wrongful Discharge from Employment Act (Mont. Code Ann. §39-2-901 et seq.).`
  }

  return `EMPLOYMENT AT WILL: Your employment with ${stateName} is at-will, meaning that either you or the company may terminate the employment relationship at any time, for any reason or no reason, with or without notice. Nothing in this letter or any other document creates a contract of employment for a specific duration or limits either party's right to terminate employment.`
}

function getComplianceNotices(state: string): string {
  const notices: Record<string, string> = {
    CA: '• California Wage Theft Prevention Act Notice (DLSE Form NTE) will be provided\n• CalSavers retirement enrollment information forthcoming\n• DFEH Rights notice enclosed\n• Paid Sick Leave (SB 616): 5 days/40 hours accrual starting on your first day',
    NY: '• NY WTPA Notice (Form LS 54 or LS 59) will be provided before first paycheck\n• NY Paid Family Leave premium will be deducted at 0.373% of wages (2024)\n• Annual sexual harassment training required per §201-g',
    TX: '• Texas Payday Law Notice will be provided per TX Lab. Code §61.013\n• Workers\' Compensation: See attached DWC-5 form regarding coverage status',
    FL: '• E-Verify participation notice (SB 1718 — required for employers with 25+ employees)\n• Workers\' Compensation coverage notice will be provided',
    CO: '• FAMLI notice: Colorado Family & Medical Leave Insurance contributions begin from first paycheck\n• COMPS Order #39 wage and hour rights enclosed',
    WA: '• Washington Paid Family & Medical Leave premium deductions begin from first paycheck\n• Washington Paid Sick Leave accrues at 1 hour per 40 hours worked'
  }

  return notices[state] || '• Federal I-9 verification required within 3 business days\n• W-4 required before first paycheck\n• State-specific notices will be provided during onboarding'
}
